[display]
	#Should the picked up amount be shown when it's just a single item.
	#Default Value: true
	display_single_count = true
	#Add the total amount of an item in your inventory to the entry.
	#Default Value: false
	inventory_count = false
	#Mode for drawing a background behind entries for better visibility. 'CHAT' is similar to the chat background, 'TOOLTIP' uses the tooltip background rendering instead.
	#Default Value: CHAT
	#Allowed Values: NONE, CHAT, TOOLTIP
	entry_background = "CHAT"
	#Add the name of the item to the entry.
	#Default Value: true
	display_item_name = true
	#Where and if to display the amount of items picked up. 'SPRITE' will render the amount on the item sprite like in inventories, 'TEXT' will add a dedicated text including the amount to the item name display.
	#Default Value: TEXT
	#Allowed Values: OFF, SPRITE, TEXT, BOTH
	display_amount = "TEXT"
	#Show a small sprite next to the name of each entry showing its contents.
	draw_sprite = true
	#Color of the entry name text.
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
	default_text_color = "WHITE"
	#Ignore rarity when determining item name color.
	ignore_rarity = false
	#Screen corner for entry list to be drawn in.
	#Allowed Values: TOP_LEFT, TOP_CENTER, TOP_RIGHT, CENTER_LEFT, CENTER, CENTER_RIGHT, BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
	screen_corner = "BOTTOM_RIGHT"
	#Offset on x-axis from screen border.
	# Default: 8
	# Range: > 0
	offset_x = 8
	#Offset on y-axis from screen border.
	# Default: 4
	# Range: > 0
	offset_y = 4
	#Percentage of relative screen height entries are allowed to fill at max.
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	max_height = 0.5
	#Scale of entries. A lower scale will make room for more rows to show. Works together with "GUI Scale" option in "Video Settings".
	# Default: 4
	# Range: 1 ~ 24
	display_scale = 4

[general]
	#Disable specific items or content from whole mods from showing.
	#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color. Begin an entry with "!" to make sure it is excluded, useful e.g. when it has already been matched by another pattern.
	#Default Value: []
	hidden_items = []
	#Show shot arrows the player has collected in the pick-up notifications.
	#Default Value: true
	include_arrows = true
	#Show item entities the player has collected in the pick-up notifications.
	#Default Value: true
	include_items = true
	#Prevent items from being added to the pick-up log when in creative mode.
	#Default Value: false
	disable_in_creative = false
	#Show experience orbs the player has collected in the pick-up notifications.
	#Default Value: true
	include_experience = true
	#Show the value of experience points collected instead of the amount of individual orbs.
	#Default Value: true
	experience_value = true
	#Force the mod to run client-side only.
	#Only enable this when there are problems, e. g. the same pick-up being logged multiple times. Partial item stack pick-ups (when the inventory is full) won't show, and backpack compatibility won't work.
	#When playing on a server without this mod this option will be used automatically.
	#Default Value: false
	client_only = false

[behavior]
	#Amount of ticks each entry will be shown for. Set to zero to only remove entries when space for new ones is needed.
	#Default Value: 80
	# Default: 80
	# Range: > 0
	display_time = 80
	#Amount of ticks it takes for an entry to move out of the screen.
	#Default Value: 20
	# Default: 20
	# Range: > 0
	move_time = 20
	#Make outdated entry names slowly fade away instead of simply vanishing.
	#Default Value: true
	fade_out = true
	#Make outdated entries slowly move out of the screen.
	#Not necessarily supported by all position presets.
	#Default Value: VERTICALLY_ONLY
	#Allowed Values: DISABLED, HORIZONTALLY_ONLY, VERTICALLY_ONLY, ENABLED
	move_out = "VERTICALLY_ONLY"
	#Combine entries of the same type instead of showing each one individually.
	#Default Value: EXCLUDE_NAMED
	#Allowed Values: ALWAYS, NEVER, EXCLUDE_NAMED
	combine_entries = "EXCLUDE_NAMED"
